### O campo requireApproval: false não pede aprovação para aplicar deploy
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/long-arcadia-413520/locations/us-east4/clusters/meu-cluster02
